[[pipeline]]
[[pipeline.agents]]
name = "generator"
model = "gpt-5-mini"
provider = "openai"
settings = { temperature = 0.1, max_retries = 2 }
prompt = "sql_prompt"
modules = ["database", "memory"]

[[pipeline]]
[[pipeline.agents]]
name = "explainer"
model = "gpt-5-mini"
provider = "openai"
settings = { temperature = 0.1, max_retries = 2 }
prompt = "nlp_prompt"
modules = ["memory"]

[[pipeline.agents]]
name = "exception"
model = "gpt-5-mini"
provider = "openai"
settings = { temperature = 0.1, max_retries = 2 }
prompt = "nlp_prompt"
modules = ["memory"]


[[edge]]
source = "START"
dest = "generator"

[[edge]]
source = "generator"
type = "conditional"
router = "redirection"

[edge.routes]
explainer = "explainer"
exception = "exception"